import {
  EventItem,
  TicketType,
  Registration,
  AttendanceBlock,
  AttendanceRecord,
  AttendanceAuditLog,
  CertificateRecord,
  EventStaff,
  CommunicationLog,
} from '../types';
import { generateTicketQRPayload } from '../utils/qr';

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt_sih_hackathon_2026',
    organizerId: 'user_sayush_org',
    organizationId: 'org_iedc_mesce',
    organizationName: 'IEDC MESCE Operations Hub',
    name: 'Smart India Hackathon (SIH) 2026 — Regional Preliminary',
    slug: 'sih-preliminary-2026',
    description:
      '36-hour intense hardware and software hackathon solving critical national infrastructure, smart cities, and healthcare challenges. Featuring live mentorship, 4-tier session attendance tracking, and verified participation certificates.',
    banner:
      'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=1600&q=80',
    category: 'Hackathon & Competitions',
    date: '2026-10-15',
    startTime: '08:30 AM',
    endTime: '06:00 PM',
    timezone: 'Asia/Kolkata (IST)',
    venue: 'Convention Center & Main Auditorium, MESCE Campus',
    location: 'Kuttippuram, Kerala, India',
    eventMode: 'IN_PERSON',
    capacity: 250,
    registeredCount: 48,
    checkedInCount: 42,
    publishedStatus: 'ONGOING',
    isTeamEvent: true,
    minTeamSize: 2,
    maxTeamSize: 4,
    registrationDeadline: '2026-10-14T23:59:00Z',
    approvalRequired: true,
    waitlistEnabled: true,
    customFormFields: [
      { id: 'f_github', label: 'GitHub Repository / Portfolio URL', type: 'text', required: true, placeholder: 'https://github.com/team' },
      { id: 'f_track', label: 'Hackathon Theme Track', type: 'select', required: true, options: ['Smart Healthcare', 'Clean Energy & EV', 'AI Automation', 'Disaster Relief'] },
      { id: 'f_hardware', label: 'Requires Hardware Lab Workbench?', type: 'checkbox', required: false },
    ],
    certificateSettings: {
      enabled: true,
      title: 'Certificate of Excellence & Completion',
      type: 'COMPLETION',
      issuerName: 'Prof. K. R. Nambiar',
      issuerDesignation: 'Chief Technology Officer & Convener',
      organizationName: 'IEDC MESCE & Ministry of Education',
      criteria: {
        rule: 'MIN_SESSIONS',
        minSessions: 3,
        minPercentage: 75,
      },
    },
    attendanceSettings: {
      allowReentry: true,
      strictBlockTiming: false,
      allowManualOverride: true,
    },
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-20T14:30:00.000Z',
  },
  {
    id: 'evt_devops_summit_2026',
    organizerId: 'user_sayush_org',
    organizationId: 'org_iedc_mesce',
    organizationName: 'IEDC MESCE Operations Hub',
    name: 'Cloud-Native & Production Kubernetes Summit',
    slug: 'cloud-native-k8s-summit',
    description:
      'Executive masterclass and engineering deep-dive on scaling microservices, eBPF observability, GitOps with ArgoCD, and automated canary deployments.',
    banner:
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80',
    category: 'Engineering & Tech Conference',
    date: '2026-10-28',
    startTime: '09:30 AM',
    endTime: '04:30 PM',
    timezone: 'Asia/Kolkata (IST)',
    venue: 'Seminar Hall 3 & Virtual Stage',
    location: 'Bangalore & Hybrid Stream',
    eventMode: 'HYBRID',
    capacity: 180,
    registeredCount: 142,
    checkedInCount: 0,
    publishedStatus: 'REGISTRATION_OPEN',
    isTeamEvent: false,
    registrationDeadline: '2026-10-26T23:59:00Z',
    approvalRequired: false,
    waitlistEnabled: true,
    customFormFields: [
      { id: 'f_exp', label: 'Cloud Experience Level', type: 'select', required: true, options: ['Student / Beginner', 'Mid-Level (1-3 yrs)', 'Senior / Staff Engineer'] },
      { id: 'f_company', label: 'Current Company / College', type: 'text', required: true },
    ],
    certificateSettings: {
      enabled: true,
      title: 'Certificate of Advanced Training',
      type: 'PARTICIPATION',
      issuerName: 'Sayush Sunesh',
      issuerDesignation: 'Director of Platform Engineering',
      organizationName: 'Cloud Native Computing Group',
      criteria: {
        rule: 'PERCENTAGE',
        minPercentage: 80,
      },
    },
    attendanceSettings: {
      allowReentry: true,
      strictBlockTiming: true,
      allowManualOverride: true,
    },
    createdAt: '2026-09-10T12:00:00.000Z',
    updatedAt: '2026-09-22T08:00:00.000Z',
  },
  {
    id: 'evt_ai_symposium_2026',
    organizerId: 'user_sayush_org',
    organizationId: 'org_iedc_mesce',
    organizationName: 'IEDC MESCE Operations Hub',
    name: 'National Generative AI & Foundation Models Symposium',
    slug: 'national-genai-symposium',
    description:
      'Exploring agentic workflows, multi-modal reasoning models, and production LLM orchestration with academic researchers and industry practitioners.',
    banner:
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=80',
    category: 'Research & AI',
    date: '2026-11-04',
    startTime: '10:00 AM',
    endTime: '05:00 PM',
    timezone: 'Asia/Kolkata (IST)',
    venue: 'Auditorium Complex, Tech Park',
    location: 'Kochi, Kerala',
    eventMode: 'IN_PERSON',
    capacity: 300,
    registeredCount: 290,
    checkedInCount: 0,
    publishedStatus: 'PUBLISHED',
    isTeamEvent: false,
    registrationDeadline: '2026-11-01T18:00:00Z',
    approvalRequired: true,
    waitlistEnabled: true,
    customFormFields: [
      { id: 'f_paper', label: 'Paper / Poster submission title (Optional)', type: 'text', required: false },
    ],
    certificateSettings: {
      enabled: true,
      title: 'Certificate of Participation & Research Presentation',
      type: 'PARTICIPATION',
      issuerName: 'Dr. S. Radhakrishnan',
      issuerDesignation: 'Head of Research, AI Foundation',
      organizationName: 'National AI Council',
      criteria: {
        rule: 'MIN_SESSIONS',
        minSessions: 2,
      },
    },
    attendanceSettings: {
      allowReentry: true,
      strictBlockTiming: false,
      allowManualOverride: true,
    },
    createdAt: '2026-09-15T09:00:00.000Z',
    updatedAt: '2026-09-21T11:20:00.000Z',
  },
];

export const INITIAL_TICKETS: TicketType[] = [
  {
    id: 'tkt_sih_team',
    eventId: 'evt_sih_hackathon_2026',
    name: 'Standard Team Pass (Free Entry)',
    description: 'Admit team of 2-4 members with full meals, 24-hour lab access, mentorship and digital passes.',
    price: 0, // Commission-free model
    capacity: 60,
    soldCount: 16,
    saleStart: '2026-09-01T00:00:00Z',
    saleEnd: '2026-10-14T23:59:00Z',
    active: true,
    perks: ['24h High-Speed Internet', 'Hardware Lab Kits', 'Verified E-Certificate', 'Catering Included'],
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'tkt_sih_vip',
    eventId: 'evt_sih_hackathon_2026',
    name: 'VIP / Mentor Delegate Pass',
    description: 'Direct lounge access, private briefing session with jury, dedicated incubation discussion.',
    price: 499, // Organizer keeps 100%, 0 commission
    capacity: 20,
    soldCount: 5,
    saleStart: '2026-09-01T00:00:00Z',
    saleEnd: '2026-10-14T23:59:00Z',
    active: true,
    perks: ['Jury Lounge Access', 'Priority Seating', 'Networking Dinner'],
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'tkt_devops_general',
    eventId: 'evt_devops_summit_2026',
    name: 'General Developer Pass',
    description: 'Full access to conference tracks, live lab access, workshop repository, and verified certificate.',
    price: 0,
    capacity: 120,
    soldCount: 95,
    saleStart: '2026-09-10T00:00:00Z',
    saleEnd: '2026-10-26T23:59:00Z',
    active: true,
    perks: ['Lab Repositories', 'Keynote Recordings', 'Digital Pass & E-Cert'],
    createdAt: '2026-09-10T12:00:00Z',
  },
];

export const INITIAL_ATTENDANCE_BLOCKS: AttendanceBlock[] = [
  {
    id: 'blk_sih_b1',
    eventId: 'evt_sih_hackathon_2026',
    title: 'Block 1: Check-in & Inaugural Keynote',
    order: 1,
    startTime: '08:30 AM',
    endTime: '10:30 AM',
    isActive: false,
    isClosed: true,
    totalPresent: 42,
    createdAt: '2026-10-15T08:00:00Z',
  },
  {
    id: 'blk_sih_b2',
    eventId: 'evt_sih_hackathon_2026',
    title: 'Block 2: Mentorship Checkpoint & Architecture Review',
    order: 2,
    startTime: '11:00 AM',
    endTime: '01:30 PM',
    isActive: false,
    isClosed: true,
    totalPresent: 38,
    createdAt: '2026-10-15T11:00:00Z',
  },
  {
    id: 'blk_sih_b3',
    eventId: 'evt_sih_hackathon_2026',
    title: 'Block 3: Prototype Demo & Mid-Way Code Evaluation',
    order: 3,
    startTime: '02:30 PM',
    endTime: '04:30 PM',
    isActive: true, // currently active session!
    isClosed: false,
    totalPresent: 34,
    createdAt: '2026-10-15T14:30:00Z',
  },
  {
    id: 'blk_sih_b4',
    eventId: 'evt_sih_hackathon_2026',
    title: 'Block 4: Final Pitch, Winner Ceremony & Closing',
    order: 4,
    startTime: '04:45 PM',
    endTime: '06:00 PM',
    isActive: false,
    isClosed: false,
    totalPresent: 0,
    createdAt: '2026-10-15T16:45:00Z',
  },
];

export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    id: 'reg_aditya_01',
    bookingId: 'BK-SIH-901',
    eventId: 'evt_sih_hackathon_2026',
    ticketId: 'tkt_sih_team',
    ticketName: 'Standard Team Pass (Free Entry)',
    pricePaid: 0,
    userId: 'user_aditya_att',
    attendeeName: 'Aditya Verma',
    attendeeEmail: 'aditya.verma@student.edu',
    attendeePhone: '+91 94471 23456',
    attendeeDept: 'Computer Science & Eng',
    attendeeCollege: 'National Institute of Tech',
    isTeam: true,
    teamId: 'team_nexus_ai',
    teamName: 'Nexus AI Innovators',
    isTeamLeader: true,
    teamMembers: [
      { name: 'Aditya Verma', email: 'aditya.verma@student.edu', phone: '+91 94471 23456' },
      { name: 'Pooja Sharma', email: 'pooja.sharma@nit.edu', phone: '+91 98822 33441' },
      { name: 'Rohan Mehra', email: 'rohan.mehra@nit.edu', phone: '+91 91122 33445' },
    ],
    customFieldsData: {
      f_github: 'https://github.com/nexus-innovators/sih-project',
      f_track: 'AI Automation',
      f_hardware: true,
    },
    status: 'APPROVED',
    physicalStatus: 'CHECKED_IN',
    qrPayload: generateTicketQRPayload('evt_sih_hackathon_2026', 'BK-SIH-901', 'reg_aditya_01'),
    checkedInAt: '2026-10-15T08:42:10Z',
    certificateEligible: true,
    certificateIssued: true,
    certificateId: 'cert_eb_2026_001',
    createdAt: '2026-09-02T14:15:00Z',
    updatedAt: '2026-10-15T08:42:10Z',
  },
  {
    id: 'reg_kavya_02',
    bookingId: 'BK-SIH-902',
    eventId: 'evt_sih_hackathon_2026',
    ticketId: 'tkt_sih_team',
    ticketName: 'Standard Team Pass (Free Entry)',
    pricePaid: 0,
    attendeeName: 'Kavya Menon',
    attendeeEmail: 'kavya.menon@mesce.ac.in',
    attendeePhone: '+91 97451 98765',
    attendeeDept: 'Electronics & Comm',
    attendeeCollege: 'MES College of Engineering',
    isTeam: true,
    teamId: 'team_circuits_green',
    teamName: 'GreenGrid Circuits',
    isTeamLeader: true,
    teamMembers: [
      { name: 'Kavya Menon', email: 'kavya.menon@mesce.ac.in' },
      { name: 'Fahad Basheer', email: 'fahad.b@mesce.ac.in' },
    ],
    customFieldsData: {
      f_github: 'https://github.com/greengrid/smart-solar',
      f_track: 'Clean Energy & EV',
      f_hardware: true,
    },
    status: 'APPROVED',
    physicalStatus: 'CHECKED_IN',
    qrPayload: generateTicketQRPayload('evt_sih_hackathon_2026', 'BK-SIH-902', 'reg_kavya_02'),
    checkedInAt: '2026-10-15T08:55:00Z',
    certificateEligible: true,
    certificateIssued: false,
    createdAt: '2026-09-03T11:00:00Z',
    updatedAt: '2026-10-15T08:55:00Z',
  },
  {
    id: 'reg_arjun_03',
    bookingId: 'BK-SIH-903',
    eventId: 'evt_sih_hackathon_2026',
    ticketId: 'tkt_sih_team',
    ticketName: 'Standard Team Pass (Free Entry)',
    pricePaid: 0,
    attendeeName: 'Arjun Das',
    attendeeEmail: 'arjun.das@coep.ac.in',
    attendeePhone: '+91 98450 11223',
    attendeeDept: 'Information Technology',
    attendeeCollege: 'COEP Tech University',
    isTeam: true,
    teamId: 'team_health_pulse',
    teamName: 'PulseCare AI',
    isTeamLeader: true,
    teamMembers: [
      { name: 'Arjun Das', email: 'arjun.das@coep.ac.in' },
      { name: 'Siddharth Rao', email: 'sid.rao@coep.ac.in' },
    ],
    customFieldsData: {
      f_github: 'https://github.com/pulsecare/ai-telemetry',
      f_track: 'Smart Healthcare',
      f_hardware: false,
    },
    status: 'APPROVED',
    physicalStatus: 'CHECKED_OUT', // Step out for lunch/hardware supplies!
    qrPayload: generateTicketQRPayload('evt_sih_hackathon_2026', 'BK-SIH-903', 'reg_arjun_03'),
    checkedInAt: '2026-10-15T08:48:30Z',
    checkedOutAt: '2026-10-15T13:20:00Z',
    certificateEligible: false,
    createdAt: '2026-09-04T09:20:00Z',
    updatedAt: '2026-10-15T13:20:00Z',
  },
  {
    id: 'reg_sneha_04',
    bookingId: 'BK-SIH-904',
    eventId: 'evt_sih_hackathon_2026',
    ticketId: 'tkt_sih_team',
    ticketName: 'Standard Team Pass (Free Entry)',
    pricePaid: 0,
    attendeeName: 'Sneha Kulkarni',
    attendeeEmail: 'sneha.k@iitm.ac.in',
    attendeePhone: '+91 93821 77665',
    attendeeDept: 'Electrical Engineering',
    attendeeCollege: 'IIT Madras',
    isTeam: true,
    teamId: 'team_resilience',
    teamName: 'DisasterMesh',
    isTeamLeader: true,
    customFieldsData: {
      f_github: 'https://github.com/disastermesh/mesh-radio',
      f_track: 'Disaster Relief',
      f_hardware: true,
    },
    status: 'APPROVED',
    physicalStatus: 'RE_ENTERED', // re-entered with pass!
    qrPayload: generateTicketQRPayload('evt_sih_hackathon_2026', 'BK-SIH-904', 'reg_sneha_04'),
    checkedInAt: '2026-10-15T08:35:12Z',
    checkedOutAt: '2026-10-15T12:45:00Z',
    reEnteredAt: '2026-10-15T14:10:20Z',
    certificateEligible: true,
    createdAt: '2026-09-04T10:10:00Z',
    updatedAt: '2026-10-15T14:10:20Z',
  },
  {
    id: 'reg_rahul_05',
    bookingId: 'BK-SIH-905',
    eventId: 'evt_sih_hackathon_2026',
    ticketId: 'tkt_sih_vip',
    ticketName: 'VIP / Mentor Delegate Pass',
    pricePaid: 499,
    attendeeName: 'Dr. Rahul Sengupta',
    attendeeEmail: 'rahul.sengupta@google.com',
    attendeePhone: '+91 99001 55443',
    attendeeDept: 'Machine Learning Research',
    attendeeCollege: 'Google Cloud Platform',
    isTeam: false,
    customFieldsData: {
      f_github: 'https://github.com/rahulsengupta',
      f_track: 'AI Automation',
    },
    status: 'APPROVED',
    physicalStatus: 'CHECKED_IN',
    qrPayload: generateTicketQRPayload('evt_sih_hackathon_2026', 'BK-SIH-905', 'reg_rahul_05'),
    checkedInAt: '2026-10-15T09:10:00Z',
    certificateEligible: true,
    createdAt: '2026-09-05T16:00:00Z',
    updatedAt: '2026-10-15T09:10:00Z',
  },
  {
    id: 'reg_waitlist_06',
    bookingId: 'BK-SIH-906',
    eventId: 'evt_sih_hackathon_2026',
    ticketId: 'tkt_sih_team',
    ticketName: 'Standard Team Pass (Free Entry)',
    pricePaid: 0,
    attendeeName: 'Meera Nambeesan',
    attendeeEmail: 'meera.nambeesan@cet.ac.in',
    attendeePhone: '+91 98470 33221',
    attendeeDept: 'Computer Science',
    attendeeCollege: 'College of Engineering Trivandrum',
    isTeam: true,
    teamId: 'team_vision_craft',
    teamName: 'VisionCraft Kerala',
    customFieldsData: { f_track: 'AI Automation' },
    status: 'WAITLISTED',
    physicalStatus: 'NOT_CHECKED_IN',
    waitlistNumber: 1,
    qrPayload: generateTicketQRPayload('evt_sih_hackathon_2026', 'BK-SIH-906', 'reg_waitlist_06'),
    createdAt: '2026-09-12T15:00:00Z',
    updatedAt: '2026-09-12T15:00:00Z',
  },
  {
    id: 'reg_pending_07',
    bookingId: 'BK-SIH-907',
    eventId: 'evt_sih_hackathon_2026',
    ticketId: 'tkt_sih_team',
    ticketName: 'Standard Team Pass (Free Entry)',
    pricePaid: 0,
    attendeeName: 'Tanvi Joshi',
    attendeeEmail: 'tanvi.joshi@vjti.ac.in',
    attendeePhone: '+91 97654 22110',
    attendeeDept: 'Data Science',
    attendeeCollege: 'VJTI Mumbai',
    isTeam: true,
    teamId: 'team_data_minds',
    teamName: 'DataMinds VJTI',
    customFieldsData: { f_track: 'Smart Healthcare' },
    status: 'PENDING',
    physicalStatus: 'NOT_CHECKED_IN',
    qrPayload: generateTicketQRPayload('evt_sih_hackathon_2026', 'BK-SIH-907', 'reg_pending_07'),
    createdAt: '2026-09-14T11:00:00Z',
    updatedAt: '2026-09-14T11:00:00Z',
  },
];

export const INITIAL_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  // Block 1 (Keynote)
  {
    id: 'att_b1_aditya',
    eventId: 'evt_sih_hackathon_2026',
    attendanceBlockId: 'blk_sih_b1',
    registrationId: 'reg_aditya_01',
    attendeeName: 'Aditya Verma',
    attendeeEmail: 'aditya.verma@student.edu',
    status: 'PRESENT',
    source: 'QR',
    actorId: 'user_ananya_staff',
    actorName: 'Ananya Nair (Staff)',
    actorRole: 'CHECK_IN_STAFF',
    timestamp: '2026-10-15T08:42:10Z',
  },
  {
    id: 'att_b1_kavya',
    eventId: 'evt_sih_hackathon_2026',
    attendanceBlockId: 'blk_sih_b1',
    registrationId: 'reg_kavya_02',
    attendeeName: 'Kavya Menon',
    attendeeEmail: 'kavya.menon@mesce.ac.in',
    status: 'PRESENT',
    source: 'QR',
    actorId: 'user_ananya_staff',
    actorName: 'Ananya Nair (Staff)',
    actorRole: 'CHECK_IN_STAFF',
    timestamp: '2026-10-15T08:55:00Z',
  },
  {
    id: 'att_b1_arjun',
    eventId: 'evt_sih_hackathon_2026',
    attendanceBlockId: 'blk_sih_b1',
    registrationId: 'reg_arjun_03',
    attendeeName: 'Arjun Das',
    attendeeEmail: 'arjun.das@coep.ac.in',
    status: 'PRESENT',
    source: 'QR',
    actorId: 'user_ananya_staff',
    actorName: 'Ananya Nair (Staff)',
    actorRole: 'CHECK_IN_STAFF',
    timestamp: '2026-10-15T08:48:30Z',
  },
  {
    id: 'att_b1_sneha',
    eventId: 'evt_sih_hackathon_2026',
    attendanceBlockId: 'blk_sih_b1',
    registrationId: 'reg_sneha_04',
    attendeeName: 'Sneha Kulkarni',
    attendeeEmail: 'sneha.k@iitm.ac.in',
    status: 'PRESENT',
    source: 'QR',
    actorId: 'user_ananya_staff',
    actorName: 'Ananya Nair (Staff)',
    actorRole: 'CHECK_IN_STAFF',
    timestamp: '2026-10-15T08:35:12Z',
  },
  {
    id: 'att_b1_rahul',
    eventId: 'evt_sih_hackathon_2026',
    attendanceBlockId: 'blk_sih_b1',
    registrationId: 'reg_rahul_05',
    attendeeName: 'Dr. Rahul Sengupta',
    attendeeEmail: 'rahul.sengupta@google.com',
    status: 'PRESENT',
    source: 'QR',
    actorId: 'user_ananya_staff',
    actorName: 'Ananya Nair (Staff)',
    actorRole: 'CHECK_IN_STAFF',
    timestamp: '2026-10-15T09:10:00Z',
  },

  // Block 2 (Mentorship)
  {
    id: 'att_b2_aditya',
    eventId: 'evt_sih_hackathon_2026',
    attendanceBlockId: 'blk_sih_b2',
    registrationId: 'reg_aditya_01',
    attendeeName: 'Aditya Verma',
    attendeeEmail: 'aditya.verma@student.edu',
    status: 'PRESENT',
    source: 'QR',
    actorId: 'user_ananya_staff',
    actorName: 'Ananya Nair (Staff)',
    actorRole: 'ATTENDANCE_MANAGER',
    timestamp: '2026-10-15T11:18:22Z',
  },
  {
    id: 'att_b2_kavya',
    eventId: 'evt_sih_hackathon_2026',
    attendanceBlockId: 'blk_sih_b2',
    registrationId: 'reg_kavya_02',
    attendeeName: 'Kavya Menon',
    attendeeEmail: 'kavya.menon@mesce.ac.in',
    status: 'PRESENT',
    source: 'QR',
    actorId: 'user_ananya_staff',
    actorName: 'Ananya Nair (Staff)',
    actorRole: 'ATTENDANCE_MANAGER',
    timestamp: '2026-10-15T11:22:15Z',
  },
  {
    id: 'att_b2_sneha',
    eventId: 'evt_sih_hackathon_2026',
    attendanceBlockId: 'blk_sih_b2',
    registrationId: 'reg_sneha_04',
    attendeeName: 'Sneha Kulkarni',
    attendeeEmail: 'sneha.k@iitm.ac.in',
    status: 'PRESENT',
    source: 'MANUAL',
    actorId: 'user_sayush_org',
    actorName: 'Sayush Sunesh (Organizer)',
    actorRole: 'ORGANIZER',
    timestamp: '2026-10-15T11:45:00Z',
  },

  // Block 3 (Mid-Way Prototype Demo)
  {
    id: 'att_b3_aditya',
    eventId: 'evt_sih_hackathon_2026',
    attendanceBlockId: 'blk_sih_b3',
    registrationId: 'reg_aditya_01',
    attendeeName: 'Aditya Verma',
    attendeeEmail: 'aditya.verma@student.edu',
    status: 'PRESENT',
    source: 'QR',
    actorId: 'user_ananya_staff',
    actorName: 'Ananya Nair (Staff)',
    actorRole: 'ATTENDANCE_MANAGER',
    timestamp: '2026-10-15T14:40:05Z',
  },
  {
    id: 'att_b3_sneha',
    eventId: 'evt_sih_hackathon_2026',
    attendanceBlockId: 'blk_sih_b3',
    registrationId: 'reg_sneha_04',
    attendeeName: 'Sneha Kulkarni',
    attendeeEmail: 'sneha.k@iitm.ac.in',
    status: 'PRESENT',
    source: 'QR',
    actorId: 'user_ananya_staff',
    actorName: 'Ananya Nair (Staff)',
    actorRole: 'ATTENDANCE_MANAGER',
    timestamp: '2026-10-15T14:45:30Z',
  },
];

export const INITIAL_AUDIT_LOGS: AttendanceAuditLog[] = [
  {
    id: 'audit_01',
    eventId: 'evt_sih_hackathon_2026',
    attendeeId: 'reg_aditya_01',
    attendeeName: 'Aditya Verma (Nexus AI Innovators)',
    attendanceBlockId: 'blk_sih_b1',
    blockTitle: 'Block 1: Check-in & Inaugural Keynote',
    actionType: 'QR_SCAN',
    actorId: 'user_ananya_staff',
    actorName: 'Ananya Nair',
    actorRole: 'CHECK_IN_STAFF',
    source: 'QR',
    timestamp: '2026-10-15T08:42:10Z',
    reason: 'Main Gate primary QR badge scan verified',
    details: 'Physical status set to CHECKED_IN. Team: Nexus AI Innovators',
  },
  {
    id: 'audit_02',
    eventId: 'evt_sih_hackathon_2026',
    attendeeId: 'reg_arjun_03',
    attendeeName: 'Arjun Das (PulseCare AI)',
    actionType: 'CHECK_OUT',
    actorId: 'user_ananya_staff',
    actorName: 'Ananya Nair',
    actorRole: 'CHECK_IN_STAFF',
    source: 'QR',
    timestamp: '2026-10-15T13:20:00Z',
    reason: 'Attendee exited main venue for hardware components procurement',
    details: 'Physical status transitioned: CHECKED_IN -> CHECKED_OUT',
  },
  {
    id: 'audit_03',
    eventId: 'evt_sih_hackathon_2026',
    attendeeId: 'reg_sneha_04',
    attendeeName: 'Sneha Kulkarni (DisasterMesh)',
    actionType: 'RE_ENTRY',
    actorId: 'user_ananya_staff',
    actorName: 'Ananya Nair',
    actorRole: 'CHECK_IN_STAFF',
    source: 'QR',
    timestamp: '2026-10-15T14:10:20Z',
    reason: 'Re-entry verified at East Gate with digital pass validation',
    details: 'Physical status transitioned: CHECKED_OUT -> RE_ENTERED',
  },
  {
    id: 'audit_04',
    eventId: 'evt_sih_hackathon_2026',
    attendanceBlockId: 'blk_sih_b3',
    blockTitle: 'Block 3: Prototype Demo & Mid-Way Code Evaluation',
    actionType: 'BLOCK_ACTIVATED',
    actorId: 'user_sayush_org',
    actorName: 'Sayush Sunesh',
    actorRole: 'ORGANIZER',
    source: 'MANUAL',
    timestamp: '2026-10-15T14:30:00Z',
    reason: 'Organizing committee commenced evaluation phase',
    details: 'Block 3 marked ACTIVE; Live scanners routing to Block 3',
  },
  {
    id: 'audit_05',
    eventId: 'evt_sih_hackathon_2026',
    attendeeId: 'reg_aditya_01',
    attendeeName: 'Aditya Verma',
    actionType: 'CERTIFICATE_GENERATED',
    actorId: 'user_sayush_org',
    actorName: 'Sayush Sunesh',
    actorRole: 'ORGANIZER',
    source: 'SYSTEM',
    timestamp: '2026-10-15T15:00:00Z',
    reason: 'Fulfilled Rule criteria: Attended 3 of required sessions (100% session progress)',
    details: 'Generated verifiable certificate ID: EASYBOOK-CERT-2026-000182',
  },
];

export const INITIAL_CERTIFICATES: CertificateRecord[] = [
  {
    id: 'cert_eb_2026_001',
    certificateNumber: 'EASYBOOK-CERT-2026-000182',
    eventId: 'evt_sih_hackathon_2026',
    eventName: 'Smart India Hackathon (SIH) 2026 — Regional Preliminary',
    registrationId: 'reg_aditya_01',
    participantName: 'Aditya Verma',
    participantEmail: 'aditya.verma@student.edu',
    certificateType: 'COMPLETION',
    status: 'VALID',
    issueDate: '2026-10-15T15:00:00Z',
    issuerName: 'Prof. K. R. Nambiar',
    issuerDesignation: 'Chief Technology Officer & Convener',
    organizationName: 'IEDC MESCE Operations Hub',
    qrVerificationUrl: 'https://easybook.platform/verify/cert_eb_2026_001',
    sessionsAttendedCount: 3,
    totalSessionsCount: 4,
    attendancePercentage: 75,
    createdAt: '2026-10-15T15:00:00Z',
  },
];

export const INITIAL_STAFF: EventStaff[] = [
  {
    id: 'staff_01',
    eventId: 'evt_sih_hackathon_2026',
    userId: 'user_ananya_staff',
    userEmail: 'ananya.staff@easybook.platform',
    userName: 'Ananya Nair',
    role: 'CHECK_IN_STAFF',
    permissions: ['QR_SCAN', 'CHECK_IN', 'CHECK_OUT', 'RE_ENTRY', 'VIEW_ATTENDEES'],
    assignedAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'staff_02',
    eventId: 'evt_sih_hackathon_2026',
    userId: 'user_sayush_org',
    userEmail: 'sayush@easybook.platform',
    userName: 'Sayush Sunesh',
    role: 'ORGANIZER',
    permissions: ['FULL_ACCESS'],
    assignedAt: '2026-09-01T10:00:00Z',
  },
];

export const INITIAL_COMMUNICATIONS: CommunicationLog[] = [
  {
    id: 'comm_01',
    eventId: 'evt_sih_hackathon_2026',
    type: 'REGISTRATION_CONFIRMATION',
    subject: 'Registration Confirmed: Smart India Hackathon 2026 (Team Pass Issued)',
    content:
      'Congratulations! Your team registration for SIH 2026 Preliminary has been approved. Your digital pass and QR code are now available in your EasyBook account.',
    recipientCount: 48,
    recipientFilter: 'All Approved Registrations',
    sentBy: 'Sayush Sunesh (Organizer)',
    sentAt: '2026-10-10T12:00:00Z',
    status: 'DELIVERED',
  },
  {
    id: 'comm_02',
    eventId: 'evt_sih_hackathon_2026',
    type: 'SESSION_ANNOUNCEMENT',
    subject: 'Session 3 Commencing: Prototype Code Evaluation at Main Hall',
    content:
      'Mentors and jury teams are now initiating Block 3 prototype evaluation. Ensure all team leaders scan their QR badges at Hall 2 checkpoint.',
    recipientCount: 42,
    recipientFilter: 'Currently Checked-in Attendees',
    sentBy: 'Ananya Nair (Staff Operations)',
    sentAt: '2026-10-15T14:25:00Z',
    status: 'DELIVERED',
  },
];
